{
 "title": "WES237A-Final-Project",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Heart Rate (bpm)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "Heart Rate",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "HEALTH",
     "select": [
      [
       { "params": [ "HR" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "HR", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Breathing Intensity",
   "type": "timeseries",
   "description": "Metric Tracking Breathing Intensity, Smaller = Short/Shallow Breaths, Larger = Longer/Deeper Breaths ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "alias": "Heart Rate",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "HEALTH",
     "select": [
      [
       { "params": [ "BREATHE" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "BREATHE", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Device Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HEALTH",
     "query": "SELECT last(\"STATUS\") FROM \"HEALTH\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "STATUS" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "STATUS", "operator": "=", "value": "last" }
     ]
    }
   ]
  },
  {
   "title": "Radar Distance (m)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"DIST\") FROM \"HEALTH\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Patient Movement Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"MOVEMENT\") FROM \"HEALTH\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Presence Detected",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"PRESENCE\") FROM \"HEALTH\" WHERE $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Range Finder Distance",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "HEALTH",
     "query": "SELECT mean(\"value\") FROM \"HEALTH\" WHERE $timeFilter GROUP BY time($__interval) fill(null)\n\n",
     "select": [
      [
       { "params": [ "ToF" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ToF", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Range Finder Placement",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HEALTH",
     "select": [
      [
       { "params": [ "ToF" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ToF", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Radar Sensor - Raw Data (Last)",
   "type": "stat",
   "description": "Most Recent Raw Data Point",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "HEALTH",
     "query": "SELECT last(\"raw\") FROM \"HEALTH\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "STATUS" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "STATUS", "operator": "=", "value": "last" }
     ]
    }
   ]
  },
  {
   "title": "Radar Sensor Raw Data",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HEALTH",
     "query": "SELECT last(\"raw\") FROM \"HEALTH\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "raw" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "raw", "operator": "=", "value": "select tag value" }
     ]
    }
   ]
  },
  {
   "title": "Distance Comparison",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "targets": [
    {
     "alias": "Radar Sensor",
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "HEALTH",
     "select": [
      [
       { "params": [ "DIST" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "DIST", "operator": ">", "value": "0" }
     ]
    },
    {
     "alias": "ToF Sensor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "HEALTH",
     "select": [
      [
       { "params": [ "ToF" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ToF", "operator": ">", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "Patient Temperature",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "degree" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10s" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "HEALTH",
     "select": [
      [
       { "params": [ "TEMP" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "TEMP", "operator": ">", "value": "0" }
     ]
    }
   ]
  }
 ]
}